import { HANDLEBARS_TEMPLATE_DIR } from "../config/persona-settings.js";

const path = HANDLEBARS_TEMPLATE_DIR;

const templateFileNames : string[] =[
	"inventory-section.hbs",
	"combat-section.hbs",
	"modifiers-section.hbs",
	"power-effects.hbs",
	"resistance-section.hbs",
	"defenses-section.hbs",
	"resistance-input.hbs",
	"defenses-input.hbs",
	"incremental-section.hbs",
	"effects-section.hbs",
	"effects-section-adaptable.hbs",
	"powers-table.hbs",
	"focii-table.hbs",
	"talents-table.hbs",
	"social-section.hbs",
	"simple-roll.hbs",
	"display-token-change.hbs",
	"disengage-check.hbs",
	"condensed-roll.hbs",
	"social-benefits-section.hbs",
	"card-events-section.hbs",
	"card-opportunity-section.hbs",
	"card-roll-section.hbs",
	"input-condition.hbs",
	"input-condition-body.hbs",
	"input-consequence.hbs",
	"input-numeric-v2.hbs",
	"input-numeric-v2-operand.hbs",
	"input-card-choice.hbs",
	"social-card-roll.hbs",
	"token-spends-section.hbs",
	"weekly-availability.hbs",
	"power-tooltip.hbs",
	"power-tooltip-lite.hbs",
	"tension-pool.hbs",
	"conditions-section.hbs",
	"consequences-section.hbs",
	"creatureTags.hbs",
	"itemTags.hbs",
	"cardTags.hbs",
	"eventTags.hbs",
	"npc-social-section.hbs",
	"npc-social-focii.hbs",
	"encounter-section.hbs",
	"npc-questions.hbs",
	"base-persona-section.hbs",
	"main-powers-table.hbs",
	"printable-mods.hbs",
	"openers-list.hbs",
	"opener-option-links.hbs",
	"damage-calc-display.hbs",
	"effects-section-tri.hbs",
	"pretty-power-name.hbs",
	"bonus-powers-table.hbs",
	"scan-sheet-header.hbs",
	"power-list.hbs",
	"learned-powers-section.hbs",
	"variable-type-specifier.hbs",
	"advanced-numeric-value.hbs",
	"persona-stats-input.hbs",
	"persona-stats-display.hbs",
	"hp-mp-section.hbs",
	"character-tab.hbs",
	"persona-stats-display.hbs",
	"social-links-list.hbs",
	"social-activities-list.hbs",
	"equipped-items.hbs",
	"inventory-list.hbs",
	"input-modifier-new.hbs",
	"persona-list.hbs",
	"persona-viewer.hbs",
	"treasure-section.hbs",
	"basic-powers-section.hbs",
	"input-conditional-boolean.hbs",
	"input-conditional-numeric.hbs",
	"input-conditional-trigger.hbs",
	"power-tags.hbs",
	"social-minor-actions.hbs",
	"talents-section.hbs",
	"navigator-skills-section.hbs",
	"next-learned-powers-section.hbs",
	"persona-list-tab.hbs",
	"fusions-list.hbs",
	"persona-compendium.hbs",
	"combat-roll-roll.hbs",
];

export const templatePaths = templateFileNames.
	map( fname => `${path}/${fname}`);

